# Generated by Django 5.1.4 on 2024-12-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingit', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='location',
            field=models.CharField(default='Banglore', max_length=100),
        ),
    ]
