# Generated by Django 3.1.12 on 2024-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingit', '0006_auto_20241222_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='location',
            field=models.CharField(default='Bangalore', max_length=100),
        ),
    ]
